### ISSUE TITLE
ERROR 560270545   Bad JSON format in file 'camp_data/reactions.json': The pointer is not associated

### ISSUE THREAD

**Issue by jolsolsen** [NCAR/music-box#104]
When I try to change values in the GUI, the issue "ERROR 560270545   Bad JSON format in file 'camp_data/reactions.json': The pointer is not associated" pops up on my screen. I have also instead tried to change the values in my reactions.json file, but it does not seem to be changing the values on the interface.

**Comment by K20shores** [comment]
Closing because we have now rewritten music-box in python and are using our musica library which is c++ based and has much more testing. This is likely no longer an issue
