### ISSUE TITLE
Add cloud mode

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box#129]
Include a cloud mode to a new test of MusicBox with conditions specified here: https://drive.google.com/drive/folders/1pFejiHbUIdQjs7DQeAa30m1U4wNluhjc

Initial conditions should be specified in the MusicBox configuration and remain constant during the simulation.

**Comment by K20shores** [comment]
Need one phase and one bin, based off of [this](https://github.com/open-atmos/camp/blob/main/test/unit_aero_rep_data/test_aero_rep_modal_binned_mass.json)
