### ISSUE TITLE
Publish images for common platforms

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box#135]
Make sure that published Docker images are provided for `linux/amd64` and `linux/arm64`

**Comment by K20shores** [comment]
Building suitesparse takes too long and the github action to publish multiplatforms times out. We can install `suitesparse-devel` and `suitesparse-static` with dnf in the docker container. However, we will need to update the search paths for suitesparse in both camp and musicbox to do that. Doing this could speed up the build, but will bump up the version of suitesparse used and could cause compiling issues if the API has changed

**Comment by K20shores** [comment]
Install paths for suitesparse: https://packages.fedoraproject.org/pkgs/suitesparse/suitesparse-devel/fedora-37.html, which don't match the variables in cmake in either musicbox or camp

**Comment by mattldawson** [comment]
not needed after moving to python
