### ISSUE TITLE
Add command-line option for running python music-box

### ISSUE THREAD

**Issue by boulderdaze** [NCAR/music-box#165]
**Acceptance Criteria**
- Add command-line option for running python music-box

**Ideas**
- The command line arguments include one configuration file, the music box configuration, along with the mechanism configuration. 
- The python installation files need to indicate that there is an executable.

**Comment by carl-drews** [comment]
Currently we have two command-line arguments:

python music_box_main.py **configFile**="C:\2024\MusicBox\music-box\tests\configs\analytical_config\my_config.json" **outputDir**="C:\2024\MusicBox\music-box\tests\configs\analytical_config"
	configFile is required; outputDir is optional and defaults to ".\\"

What is the "mechanism configuration"?

**Comment by boulderdaze** [comment]
My understanding is that the mechanism configuration is a configuration that has reaction information ([this](https://github.com/NCAR/music-box/blob/main/tests/configs/analytical_config/camp_data/reactions.json) is an example of mechanism configuration).  
But for this case, it looks like the path `outputDir="C:\2024\MusicBox\music-box\tests\configs\analytical_config"`includes the directory that has mechanism configuration. `outputDir="C:\2024\MusicBox\music-box\tests\configs\analytical_config\camp_data\"` 
I guess I can't really answer it.. Hi @K20shores, could you answer this question?

**Comment by boulderdaze** [comment]
Wait, this `"C:\2024\MusicBox\music-box\tests\configs\analytical_config\"` looks like an input from the user instead of being output dir. Could you confirm this?

**Comment by carl-drews** [comment]
The intent is to read a configuration from here:
C:\2024\MusicBox\music-box\tests\configs\analytical_config\my_config.json

and place the solved output into the same directory here:
C:\2024\MusicBox\music-box\tests\configs\analytical_config\mySolution.csv

So far in my experience, the files in camp_data are specified in my_config.json, and do not need an additional argument.

**Comment by K20shores** [comment]
#172 addressed this
