### ISSUE TITLE
Air density should be passed to MICM solve function

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box#169]
The air density [mol m-3] should be passed to the `musica.micm_solve()` function, similar to temperature and pressure. The calculation of air density should be based on the ideal gas law.

Blocked by https://github.com/NCAR/musica/issues/157

**Acceptance Criteria**
- Air density based on the specified temperature and pressure using the ideal gas law is passed to the `musica.micm_solve()` function at each time step

**Ideas**
- Use the same algorithm as for calculating `[M]` to get the air density: https://github.com/NCAR/music-box/blob/589377b47751d1642d075022918699eb7cf592be/src/acom_music_box/music_box.py#L513-L517
- Instead of calculating `[M]`, change it's `"tracer type"` to `"THIRD_BODY_SPECIES"` in the configuration data, and let MICM set its value based on the specified air density. See here: https://github.com/NCAR/micm/blob/854ca2db7ea2a70cb72541a2436300c327e51578/test/unit/unit_configs/third_body/species.json#L7-L11

**Comment by carl-drews** [comment]
>Instead of calculating [M], change it's "tracer type" to "THIRD_BODY_SPECIES" in the configuration data, and let MICM set its value based on the specified air density. <

The "tracer type" of the camp-data? As read from species.json?

**Comment by mattldawson** [comment]
> > Instead of calculating [M], change it's "tracer type" to "THIRD_BODY_SPECIES" in the configuration data, and let MICM set its value based on the specified air density. <
> 
> The "tracer type" of the camp-data? As read from species.json?

Yes. My suggestion would be to have the python code add a species to the `species.json` file called `M` with a `tracer type`: `THIRD_BODY`. If a species `M` exists in already in `species.json`, I think we should return an error that says that a species named `M` is reserved for third-body species.

The species `M` (because it is a `THIRD_BODY` `tracer type`) will not appear in the `species_ordering` list because it is parameterized.

**Comment by carl-drews** [comment]
Thank you @mattldawson. This approach is reminiscent of TUV-x. I will proceed. :-)

**Comment by carl-drews** [comment]
I tried adding the M to species.json directly as a first step:
```
        {
            "name": "irr__2a109b21-bb24-41ae-8f06-7485fd36f1a7",
            "type": "CHEM_SPEC"
        },
	**{
            "name": "M",
            "tracer type": "THIRD_BODY"
        }**
```

I get this error:
  File "C:\Users\drews\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\acom_music_box\music_box.py", line 420, in create_solver
    self.solver = musica.create_solver(path_to_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error creating solver: object: {"name":"M","tracer type":"THIRD_BODY"}; type: type: Object type not found

Does musica have to know about the new "tracer type" here?

**Comment by carl-drews** [comment]
musica.micm_solve() returns without known errors if I create the M species in Python as the final step before solving:
```
            mSpecies = Species(name="M")
            mSpecies.tracer_type = "THIRD_BODY_SPECIES"
            self.species_list.species.append(mSpecies)
```

However, there is no change in M after micm_solve(), so I must still be missing something.
`INFO:acom_music_box.music_box:M species 34567 {'name': 'M', 'absolute_tolerance': None, 'phase': None, 'molecular_weight': None, 'density': None, 'tracer_type': 'THIRD_BODY_SPECIES'}`

**Comment by K20shores** [comment]
So I guess there are at least two issues. One is that we aren't seeing any useful error message, another is that we can't proceed with solving. I will try to send out a release today or tomorrow that will hopefully solve the error message problem. Then maybe that will help us move this further along

**Comment by K20shores** [comment]
For reference, we have a test of [chapman](https://github.com/NCAR/musica/blob/main/python/test/test_chapman.py) using the python wrapper in musica which reads [this configuration](https://github.com/NCAR/musica/tree/main/configs/chapman) and there M is not marked as a third body species. So it seems we need to update our test case in musica. I will do that with the release

**Comment by carl-drews** [comment]
With this configuration of M in music-box/tests/configs/analytical_config/camp_data/species.json:
	    {
            "name": "M",
            "type": "CHEM_SPEC",
            "tracer type": "CONSTANT",
	    "__description": "third-body species"
        },

musica.micm_solve() succeeds and passes back a solution. mySolution.csv has a column CONC.M, but that column is all zeros. Isn't MICM supposed to set the value of M based on the air_density parameter? Calculated at 44.68980861228497?

**Comment by K20shores** [comment]
@carl-drews my PR in #178 uses musica 0.7.3 with `THIRD_BODY` successfully, perhaps you still have an old version of musica?

**Comment by carl-drews** [comment]
My version of musica is now fixed at 0.7.3 for music-box after fixing the pyproject.toml file.

I can run chapman_config successfully with species.json including:
        {
            "name": "M",
            "type": "CHEM_SPEC",
            "tracer type": "THIRD_BODY"
        },

But my solution has CONC.M = 0.0 for all time steps. Isn't MICM supposed to set that to the air density?

**Comment by K20shores** [comment]
It is supposed to set the air density. I think you can remove any setting of the M concentration

**Comment by K20shores** [comment]
I believe I had to do that in #178, though I don't really remember now

**Comment by carl-drews** [comment]
This issue is addressed in Pull Request 186: https://github.com/NCAR/music-box/pull/186

**Comment by carl-drews** [comment]
Resolved and merged with main branch.
