### ISSUE TITLE
MusicBox with TUV photolysis (Use Case 10)

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box#17]
### Use case 10: Simple box model with TUV photolysis

The user wants to run a simple 48-hour (or any length of time) box model run with TUV photolysis. No input data exists for this scenario, so the user creates a NetCDF file in the native MusicBox format for a column of grid cells with the initial chemical species concentrations in each cell, and names the file `my_initial_conditions.nc`. They also create a `my_evolving_conditions.nc` file (also in the native MusicBox format) for 24-hour profiles of temperature, pressure, and methane and formaldehyde concentrations for each grid cell in the column and a 24-hour profile of solar zenith angle for the column, all at 2-hour intervals (or any interval they want). The environmental conditions will be reused every 24 hours to make up the 48-hour simulation time.

To run this scenario, they first copy the two NetCDF files to the `configuration/` folder they created (see page 1 workflow) and write a `my_config.json` file that looks like this:
```
{
  “initial conditions” : {
    “my_initial_conditions.nc” : {}
  },
  “evolving conditions” : {
    “my_evolving_conditions.nc” : {
      “cycle time [hr]” : 24
    }
  },
  “box model options” : {
    “grid”                      : “column”,
    “pressure [Pa]”             : 101325.0,
    “chemistry time step [min]” : 5.0,
    “output time step [hr]”     : 1.0,
    “simulation length [hr]”    : 48.0
  },
  “photolysis module” : { “TUV” : { } }
}
```

They then follow the remainder of the workflow on page 1.

**NOTES:**
- Because MusicBox has a standard csv and a standard NetCDF format, input files with a `.nc` extension (unless otherwise specified) are assumed to be in the standard format—i.e., species names, environmental condition names (temperature, pressure, etc.) and units are all in the standard MusicBox format.
- For box model configuration properties (in this case, the time steps), MusicBox recognizes several unit abbreviations (here, min and hr, but also s, sec, m, h, hour, etc.) and makes the appropriate conversions.
- Because TUV requires a column of data, if only a single grid cell is present in the input data, an error is returned when the model is run.
- The order of the elements of the configuration file is arbitrary—e.g., it could have been box model options, then initial conditions, then photolysis, etc.
- If any required property (e.g., temperature) is not present in any of the input data files and is not set in the configuration file to a constant or scaled value, then an error is returned when the model is run.
- The input data (in this case, at 2-hour intervals) will be linearly interpolated to the chemistry time step (here, 5.0 min).
- When the NetCDF library is used during the MusicBox build, the default output is NetCDF. However, output in ASCII csv files can be specified.
- The simulation start time is assumed to be the earliest start time of the evolving input data, unless otherwise specified.
- The default output file name for NetCDF output is `MusicBox_output.nc`, but this can be changed in the configuration file.
- To specify ASCII output to a file named `my_output.csv`, you would add this to the my_config.json:
```
      “output file” : { “format” : “CSV”, “name” : “my_output.csv” }
```
- The specified pressure is used to identify the vertical layer to use for the box model
- The vertical layer is identified based on conditions at the start of the simulation and does not change during the simulation

**Comment by mattldawson** [comment]
Hi @fvitt - let me know when you're ready to try to start using the refactored TUV in MusicBox 2.0 and maybe we can do it as part of this issue

**Comment by zmoon** [comment]
Is there an example or something with this use case now? (noticed the recent closure)

**Comment by K20shores** [comment]
@zmoon not yet. We have not had time to finish the python side of TUV. I'll be sure to ping you when we get an example working.
