### ISSUE TITLE
Create a script that extracts information from WACCM simulation output to use as inputs to MusicBox

### ISSUE THREAD

**Issue by mattldawson** [NCAR/music-box#184]
Create a script that extracts information from WACCM simulation output to use as inputs to MusicBox. An example script that does something similar for BoxMox inputs can be found [here](https://drive.google.com/file/d/1fFygS9DdFYwaY5_zAlnKz0NjdxMwDmAw/view?usp=drive_link)

**Acceptance Criteria**
- Given location, time, and pressure level, extract initial conditions from TS1
  - may be able to leverage this script to start [boxmox_acclip_nox_v3.py.zip](https://github.com/user-attachments/files/16591570/boxmox_acclip_nox_v3.py.zip)
- To start, get conditions according to these parameters
  - Location: Kuala Lumpur, Malaysia   3.1N, 101.7E
  - Date: March 1, 2024 
  - Time: 0000 LT 
  - 24-hour simulation

**Comment by carl-drews** [comment]
Where shall I place **waccmToMusicBox.py** within our github repository? Here with the other python code files?
https://github.com/NCAR/music-box/tree/main/src/acom_music_box

The only distinction is that waccmToMusicBox.py has its own main().

**Comment by K20shores** [comment]
I would recomend putting it in either `etc` or `tools`, but still add it as an executable command that people can run in our `pyproject.toml` file

**Comment by carl-drews** [comment]
How does "24-hour simulation" relate to "initial conditions"? Should the CSV file have 24 rows, each representing another hour after March 1, 2024 at 00:00 Local Time?

**Comment by K20shores** [comment]
@carl-drews The initial conditions for temperature, pressure, and the species concnetrations need to be pulled from some WACCM output at a particular time and location. The 24 hour part has nothing to do with the rest of the WACCM output, or that's my understanding

**Comment by carl-drews** [comment]
Carl Drews
  10:54 PM
waccmToMusicBox.py is ready for review on this branch:
https://github.com/NCAR/music-box/tree/tools-waccm/tools
def getMusicaDictionary(): has just my wild guesses as what variables we might use. Feel free to modify that dictionary extensively.

Sorry, I forgot to add temperature and pressure to the dictionary. :-(
