### ISSUE TITLE
Some examples in music-box-interactive-api do not run correctly under Musica 0.7.3

### ISSUE THREAD

**Issue by carl-drews** [NCAR/music-box#187]
Some of the JSON configurations are not compatible with the python music-box and musica 0.7.3. For example, I made these corrections while testing:

--- a/interactive/api/static/examples/FLOW_TUBE/camp_data/config.json
+++ b/interactive/api/static/examples/FLOW_TUBE/camp_data/config.json
@@ -1,7 +1,7 @@
 {
   "camp-files" : [
-    "camp_data/species.json",
-    "camp_data/reactions.json",
-       "camp_data/tolerance.json"
+    "species.json",
+    "reactions.json",
+       "tolerance.json"
   ]
 }

--- a/interactive/api/static/examples/FLOW_TUBE/camp_data/species.json
+++ b/interactive/api/static/examples/FLOW_TUBE/camp_data/species.json
@@ -3,8 +3,7 @@
     {
       "name": "M",
       "type": "CHEM_SPEC",
-      "tracer type": "CONSTANT",
-      "description": "Third-body molecule. This is any molecule present in the system."
+      "tracer type": "CONSTANT"
     },

That is not an exhaustive list. Do we desire to make these corrections now or later?

**Comment by carl-drews** [comment]
See also:
 Validate all configuration in MusicBox curriculum examples #161 
https://github.com/NCAR/music-box/issues/161

**Comment by K20shores** [comment]
Music box interactive (specifically the API server) generates (and stores) configurations with the path `camp_data/species.json`. We need to decide if we need to make music-box conform to the api server, or the other way around. @mattldawson what do you think?

**Comment by K20shores** [comment]
All examples are now passing on main
