### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box#38]
This model needs an introductory guide or user's guide.  It should be part of the released docker-hub image.  It should include instructions for:
- running the model
- documentation sources for more diverse questions
- minor changes to the mechanism (rate constants)
- major changes to the mechanism
- accessing other mechanisms
- changing the environmental conditions
- what else?

**Comment by AndrewJConley** [comment]
I think we need a video on installing and using Docker.  Or perhaps a link to someone's video that is appropriate to our needs.
 
Also we need a video on needs of the model.  Such a video would need regular updating.

And perhaps a video on community standards, standards for code that is to be included, and development paradigms.

**Comment by lkemmons** [comment]
@mattldawson @K20shores I have found helpful documentation in several places - could they be consolidated?
https://github.com/NCAR/music-box/blob/main/config_options.md
https://github.com/NCAR/musicbox_curriculum_exercises/blob/main/musicbox_student_help.md
The documentation currently in the doxygen_files in ./doc/ is very sparse.  Can we start a readthedocs site for this documentation - it is rather inconvenient to have to figure out how to create the doxygen documentation.

**Comment by K20shores** [comment]
Closing in favor of #163
