### ISSUE TITLE
Missing plots for Reaction Rates

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box#54]
After running the code, using the GUI, the plots for the molecule concentrations are there, but there are no reaction rates to plot.

**Comment by s-omas** [comment]
Reaction rates are not in the CSV output file so not being displayed by the interface

**Comment by AndrewJConley** [comment]
Perhaps we need an indication that "no rates were produced by this model".  What do you think?

**Comment by s-omas** [comment]
Should reaction rates always be in the output? or is that something that can change? I can make the 'reaction rates' tab only show up if there are any in the output

**Comment by mattldawson** [comment]
that's probably the best option - reaction rates aren't currently output by CAMP

**Comment by AndrewJConley** [comment]
I agree.  Let's hide tabs for plots of non-existent data.
