### ISSUE TITLE
Missing data when the model starts to run

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box#60]
<img width="450" alt="Screen Shot 2021-02-04 at 3 19 43 PM" src="https://user-images.githubusercontent.com/8648491/106966195-1c75a680-6702-11eb-957d-33a6367e575a.png">

I have intermittent problems where this error pops up when I hit the "run" button.

**Comment by mattldawson** [comment]
I believe this is because the initial species concentration list starts with a blank line with 'Enter Formula' as the species name. If you don't set any initial species concentrations, this error pops up. I'll work on this

**Comment by mattldawson** [comment]
I think this is fixed now. I updated music-box with the latest commits to interactive. Could you give it a try and see if it works now?

**Comment by AndrewJConley** [comment]
This error is no longer seems to be present
