### ISSUE TITLE
Example case 1, names of species for initial conditions

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box#65]
The names of the species are not shown for the initial conditions.
<img width="1301" alt="Screen Shot 2021-02-17 at 1 34 05 PM" src="https://user-images.githubusercontent.com/8648491/108264646-07970b00-7125-11eb-909e-2205bf6c454a.png">

**Comment by mattldawson** [comment]
hi @AndrewJConley - I just tested this with the latest DockerHub image, and the species names show up for me. Could you include the steps after starting up the Docker container to recreate this? (including the browser you're using)
