### ISSUE TITLE
Sponsors and Partners

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/music-box#66]
At the moment, our only sponsor is NSF.

We (according to Gabi) don't have any partners.

Let's reduce the sponsorship page to NSF for right now.
Let's remove the "Partners"

Let's add a page for "Contributors" that has all the other groups and institutions.

**Comment by mattldawson** [comment]
What about a sub-section of sponsors called "Contributor Sponsors"?

**Comment by AndrewJConley** [comment]
Sponsorship through Contributions ?

Collaborators?

I like Collaborators.

**Comment by mattldawson** [comment]
Collaborators sounds good

**Comment by AndrewJConley** [comment]
Collaborators it is!

**Comment by mattldawson** [comment]
recreated this issue in music-box-interactive
